///////////////////////////////////////////////////////////
//  Agente.cs
//  Implementation of the Class Agente
//  Generated by Enterprise Architect
//  Created on:      08-set-2012 11:05:49
///////////////////////////////////////////////////////////




namespace System {
	public class Agente {

		private int ID_Agente;
		private int _ID_Projeto;
		private string _Nome;
		private string _CPF;
		private string _CNPJ;
		private string _Email;
		private int _DDD;
		private string _Telefone;
		private int _DDD_Celular;
		private string _Celular;
		private date _DataNascimento;
		private string _Endereço;
		private string _Complemento;
		private string _CEP;
		private string _Cidade;
		private string _UF;
		private string _Sexo;

		public Agente(){

		}

		~Agente(){

		}

		public virtual void Dispose(){

		}

		public int ID_Projeto{
			get{
				return ID_Projeto;
			}
			set{
				ID_Projeto = value;
			}
		}

		public string Nome{
			get{
				return Nome;
			}
			set{
				Nome = value;
			}
		}

		public int CPF{
			get{
				return _CPF;
			}
			set{
				_CPF = value;
			}
		}

		public string CNPJ{
			get{
				return _CNPJ;
			}
			set{
				_CNPJ = value;
			}
		}

		public string Email{
			get{
				return Email;
			}
			set{
				Email = value;
			}
		}

		public int DDD{
			get{
				return _DDD;
			}
			set{
				_DDD = value;
			}
		}

		public string Telefone{
			get{
				return _Telefone;
			}
			set{
				_Telefone = value;
			}
		}

		public int DDD_Celular{
			get{
				return _DDD_Celular;
			}
			set{
				_DDD_Celular = value;
			}
		}

		public string Celular{
			get{
				return Celular;
			}
			set{
				Celular = value;
			}
		}

		public string Endereço{
			get{
				return _Endereço;
			}
			set{
				_Endereço = value;
			}
		}

		public int Complemento{
			get{
				return _Complemento;
			}
			set{
				_Complemento = value;
			}
		}

		public string CEP{
			get{
				return _CEP;
			}
			set{
				_CEP = value;
			}
		}

		public string Cidade{
			get{
				return _Cidade;
			}
			set{
				_Cidade = value;
			}
		}

		public string UF{
			get{
				return _UF;
			}
			set{
				_UF = value;
			}
		}

		public string Sexo{
			get{
				return _Sexo;
			}
			set{
				_Sexo = value;
			}
		}

		public void Incluir(){

		}

		public void Alterar(){

		}

		/// 
		/// <param name="ID_Agente"></param>
		public void Selecionar(int ID_Agente){

		}

		/// 
		/// <param name="ID_Agente"></param>
		public bool Excluir(int ID_Agente){

			return false;
		}

		/// 
		/// <param name="ID_Projeto"></param>
		public List Listar(int ID_Projeto){

			return null;
		}

	}//end Agente

}//end namespace System