///////////////////////////////////////////////////////////
//  Custo.cs
//  Implementation of the Class Custo
//  Generated by Enterprise Architect
//  Created on:      05-set-2012 22:00:40
//  Original author: Miza
///////////////////////////////////////////////////////////




namespace System {
	public class Custo {

		private int ID_Custo;
		private int _ID_Projeto;
		private string _Descricao;
		private decimal _CustoEstimado;
		private string _Justificativa;
		private date _Data;

		public Custo(){

		}

		~Custo(){

		}

		public virtual void Dispose(){

		}

		public int ID_Projeto{
			get{
				return _ID_Projeto;
			}
			set{
				_ID_Projeto = value;
			}
		}

		public string Descricao{
			get{
				return _Descricao;
			}
			set{
				_Descricao = value;
			}
		}

		public decimal CustoEstimado{
			get{
				return _CustoEstimado;
			}
			set{
				_CustoEstimado = value;
			}
		}

		public string Justificativa{
			get{
				return _Justificativa;
			}
			set{
				_Justificativa = value;
			}
		}

		public date Data{
			get{
				return _Data;
			}
			set{
				_Data = value;
			}
		}

		public void Inserir(){

		}

		public void Alterar(){

		}

		/// 
		/// <param name="ID_Custo"></param>
		public void Selecionar(int ID_Custo){

		}

		/// 
		/// <param name="ID_Custo"></param>
		public bool Excluir(int ID_Custo){

			return false;
		}

		/// 
		/// <param name="ID_Projeto"></param>
		public void Listar(int ID_Projeto){

		}

	}//end Custo

}//end namespace System