///////////////////////////////////////////////////////////
//  Investidor.cs
//  Implementation of the Class Investidor
//  Generated by Enterprise Architect
//  Created on:      05-set-2012 23:46:05
///////////////////////////////////////////////////////////




using System;
namespace System {
	public class Investidor {

		private int ID_Investidor;
		private string _Nome;
		private string _CPF;
		private string _WebPage;
		private string _Email;
		private int _DDD;
		private string _Telefone;
		private int _DDD_Celular;
		private string _Celular;
		private date _DataNascimento;
		private string _Endereço;
		private string _Complemento;
		private string _CEP;
		private int _Cidade;
		private string _UF;
		private string _Sexo;
		public Projeto m_Projeto;

		public Investidor(){

		}

		~Investidor(){

		}

		public virtual void Dispose(){

		}

		public string Nome{
			get{
				return _Nome;
			}
			set{
				_Nome = value;
			}
		}

		public string CPF{
			get{
				return _CPF;
			}
			set{
				_CPF = value;
			}
		}

		public string WebPage{
			get{
				return _WebPage;
			}
			set{
				_WebPage = value;
			}
		}

		public string Email{
			get{
				return _Email;
			}
			set{
				_Email = value;
			}
		}

		public int DDD{
			get{
				return _DDD;
			}
			set{
				_DDD = value;
			}
		}

		public string Telefone{
			get{
				return _Telefone;
			}
			set{
				_Telefone = value;
			}
		}

		public int DDD_Celular{
			get{
				return _DDD_Celular;
			}
			set{
				_DDD_Celular = value;
			}
		}

		public string Celular{
			get{
				return _Celular;
			}
			set{
				_Celular = value;
			}
		}

		public string Endereço{
			get{
				return _Endereço;
			}
			set{
				_Endereço = value;
			}
		}

		public string Complemento{
			get{
				return _Complemento;
			}
			set{
				_Complemento = value;
			}
		}

		public string CEP{
			get{
				return _CEP;
			}
			set{
				_CEP = value;
			}
		}

		public int Cidade{
			get{
				return _Cidade;
			}
			set{
				_Cidade = value;
			}
		}

		public string UF{
			get{
				return UF;
			}
			set{
				UF = value;
			}
		}

		public string Sexo{
			get{
				return _Sexo;
			}
			set{
				_Sexo = value;
			}
		}

		public void Inserir(){

		}

		public void Alterar(){

		}

		/// 
		/// <param name="ID_Investidor"></param>
		public void Selecionar(int ID_Investidor){

		}

		public List ListarProjetosInvestidos(){

			return null;
		}

	}//end Investidor

}//end namespace System