///////////////////////////////////////////////////////////
//  Mensagem.cs
//  Implementation of the Class Mensagem
//  Generated by Enterprise Architect
//  Created on:      05-set-2012 23:49:07
//  Original author: Miza
///////////////////////////////////////////////////////////




using System;
namespace System {
	public class Mensagem {

		private int ID_Mensagens;
		private int _ID_Projeto;
		private bool _FlagAgenteOuInvestidor;
		private string _Texto;
		private string _Titulo;
		private date _Data;
		private string _Usuario;
		public Agente m_Agente;
		public Investidor m_Investidor;

		public Mensagem(){

		}

		~Mensagem(){

		}

		public virtual void Dispose(){

		}

		public int ID_Projeto{
			get{
				return ID_Projeto;
			}
			set{
				ID_Projeto = value;
			}
		}

		public bool FlagAgenteOuInvestidor{
			get{
				return _FlagAgenteOuInvestidor;
			}
			set{
				_FlagAgenteOuInvestidor = value;
			}
		}

		public string Texto{
			get{
				return _Texto;
			}
			set{
				_Texto = value;
			}
		}

		public string Titulo{
			get{
				return _Titulo;
			}
			set{
				_Titulo = value;
			}
		}

		public date Data{
			get{
				return _Data;
			}
			set{
				_Data = value;
			}
		}

		public string Usuario{
			get{
				return _Usuario;
			}
			set{
				_Usuario = value;
			}
		}

		/// 
		/// <param name="FlagAgenteOuInvestidor"></param>
		/// <param name="ID"></param>
		public void Listar(bool FlagAgenteOuInvestidor, int ID){

		}

		/// 
		/// <param name="ID_Mensagem"></param>
		public void Selecionar(int ID_Mensagem){

		}

	}//end Mensagem

}//end namespace System