///////////////////////////////////////////////////////////
//  Projeto.cs
//  Implementation of the Class Projeto
//  Generated by Enterprise Architect
//  Created on:      05-set-2012 23:58:02
//  Original author: Miza
///////////////////////////////////////////////////////////




using System;
using Tabelas;
namespace System {
	public class Projeto : Projetos {

		private int ID_Projeto;
		private string _NomeProjeto;
		private string _DescricaoProjeto;
		private string _ImagemProjeto;
		private string _VideoProjeto;
		private string _PerfilProjeto;
		private string _RamoAtividade;
		private int _Ranking;
		private decimal _Custo_Projeto;
		private int _Porcentagem;
		public Lucro m_Lucro;
		public Documento m_Documento;
		public Agente m_Agente;

		public Projeto(){

		}

		~Projeto(){

		}

		public override void Dispose(){

		}

		public void Inserir(){

		}

		public void Alterar(){

		}

		/// 
		/// <param name="ID_Projeto"></param>
		public bool Seleciona(int ID_Projeto){

			return false;
		}

		/// 
		/// <param name="NomeProjeto"></param>
		public string NomeProjeto{
			get{
				return _NomeProjeto;
			}
			set{
				_NomeProjeto = value;
			}
		}

		public string DescricaoProjeto{
			get{
				return _DescricaoProjeto;
			}
			set{
				_DescricaoProjeto = value;
			}
		}

		public string ImagemProjeto{
			get{
				return _ImagemProjeto;
			}
			set{
				_ImagemProjeto = value;
			}
		}

		public string VideoProjeto{
			get{
				return _VideoProjeto;
			}
			set{
				_VideoProjeto = value;
			}
		}

		public string PerfilProjeto{
			get{
				return _PerfilProjeto;
			}
			set{
				_PerfilProjeto = value;
			}
		}

		public string RamoAtividade{
			get{
				return _RamoAtividade;
			}
			set{
				_RamoAtividade = value;
			}
		}

		public int Ranking{
			get{
				return _Ranking;
			}
			set{
				_Ranking = value;
			}
		}

		public decimal Custo_Projeto{
			get{
				return Custo_Projeto;
			}
			set{
				Custo_Projeto = value;
			}
		}

		/// 
		/// <param name="ID_Investidor"></param>
		/// <param name="Valor"></param>
		public bool InvestirProjeto(int ID_Investidor, decimal Valor){

			return false;
		}

		/// 
		/// <param name="where"></param>
		/// <param name="Perfil"></param>
		/// <param name="Industria"></param>
		/// <param name="Varejo"></param>
		/// <param name="Artistico"></param>
		/// <param name="TI"></param>
		/// <param name="PowerPoint"></param>
		/// <param name="Video"></param>
		/// <param name="Audio"></param>
		public List Listar(string where, string Perfil, bool Industria, bool Varejo, bool Artistico, bool TI, bool PowerPoint, bool Video, bool Audio){

			return null;
		}

		public int Porcentagem{
			get{
				return _Porcentagem;
			}
			set{
				_Porcentagem = value;
			}
		}

		/// 
		/// <param name="ID_Investidor"></param>
		/// <param name="Nota"></param>
		public bool VotarProjeto(int ID_Investidor, int Nota){

			return false;
		}

		/// 
		/// <param name="NomeProjeto"></param>
		public string NomeProjeto{
			get{
				return _NomeProjeto;
			}
			set{
				_NomeProjeto = value;
			}
		}

	}//end Projeto

}//end namespace System