///////////////////////////////////////////////////////////
//  ProjetosVisitados.cs
//  Implementation of the Class ProjetosVisitados
//  Generated by Enterprise Architect
//  Created on:      06-set-2012 17:54:59
//  Original author: Tiago
///////////////////////////////////////////////////////////




using System;
namespace System {
	public class ProjetosVisitados {

		private int ID_ProjetoVisitados;
		private int _ID_Projeto;
		private int _ID_Investidor;
		private date _Data;
		private string _Hora;
		public Projeto m_Projeto;
		public Investidor m_Investidor;

		public ProjetosVisitados(){

		}

		~ProjetosVisitados(){

		}

		public virtual void Dispose(){

		}

		public int getID_Projeto(){

			return 0;
		}

		/// 
		/// <param name="newVal"></param>
		public void setID_Projeto(int newVal){

		}

		public int getID_Investidor(){

			return 0;
		}

		/// 
		/// <param name="newVal"></param>
		public void setID_Investidor(int newVal){

		}

		public date getData(){

			return null;
		}

		/// 
		/// <param name="newVal"></param>
		public void setData(date newVal){

		}

		public string getHora(){

			return "";
		}

		/// 
		/// <param name="newVal"></param>
		public void setHora(string newVal){

		}

		public void Inserir(){

		}

		/// 
		/// <param name="ID_Investidor"></param>
		public List Lista(boolean ID_Investidor){

			return null;
		}

	}//end ProjetosVisitados

}//end namespace System